### ISSUE TITLE
[Question] How to show arg option in other language instead of English

### ISSUE THREAD

**Issue by wellitecho** [MichalGniadek/klask#20]
Thanks for your hard work on this crate. It's extremely quick to use.

I wonder if it's possible to show the cli arg in other language, say, in Chinese, in the gui, since the user of my small app does not know English.
A simple example would be, the app has an arg 'file_path', and I want it displayed as '文件路径' to the user, which means exactly 'file_path' in Chinese.

Thanks in advance for your help.

**Comment by MichalGniadek** [comment]
Hi, could you try to use `klask = { git = "https://github.com/MichalGniadek/klask", branch = "custom-fonts" }` in your `cargo.toml`? I added the option to specify a custom font in the `Setting`s, so you can use a font that supports Chinese or other languages. Here's an example:
```rust
use clap::{Parser, ValueHint};
use klask::Settings;
use std::path::PathBuf;

#[derive(Parser)]
struct Font {
    #[clap(long, value_hint = ValueHint::AnyPath)]
    文件路径: PathBuf,
}

fn main() {
    let settings = Settings {
        custom_font: Some(include_bytes!(r"C:\WINDOWS\FONTS\ARIALUNI.TTF")),
        ..Default::default()
    };

    klask::run_derived::<Font, _>(settings, |_| {});
}

```

**Comment by wellitecho** [comment]
Thanks! I just ran your example, it worked. Only it's weird that I need to get the path value with something like **f.文件路径**. I have to say, it's the first time I knew that in Rust this even works...
![screenshot](https://user-images.githubusercontent.com/79682683/140605004-87715244-7522-47f7-b6d4-2952cabfb5aa.png)

**Comment by MichalGniadek** [comment]
Yeah, rust supports Unicode identifiers! But you can do something like this
```rust
#[derive(Parser)]
struct Font {
    #[clap(long, name = "文件路径", value_hint = ValueHint::AnyPath)]
    file_path: PathBuf,
}
```
to get a custom name in the gui but also an English field name.

**Comment by wellitecho** [comment]
Thank you for putting time into this. I'm really grateful! This solved the problem. I will close the issue then.
