### ISSUE TITLE
Replace environment variable lookup by --gui / --cli flag

### ISSUE THREAD

**Issue by Eolien55** [MichalGniadek/klask#22]
Thanks again for the work you've put into Klask.

I think that we should replace the environment variable `KLASK_CHILD_APP` by a --gui / --cli flag. This would allow to have only one binary for both graphical and command line interfaces.

Cheers

**Comment by MichalGniadek** [comment]
Hi, would something like this work for you?
```
use clap::{AppSettings, Arg, IntoApp, Parser};
use klask::Settings;

#[derive(Debug, Parser)]
struct App {
    #[clap(long)]
    gui: bool,
    foo: String,
    bar: String,
}

fn main() {
    // Use IgnoreErrors so we don't have to specify foo and bar when using "--gui"
    let a = App::into_app()
        .setting(AppSettings::IgnoreErrors)
        .get_matches();
    if a.is_present("gui") {
        // klask ignores any args names "help"
        let app = App::into_app().mut_arg("gui", |_| Arg::new("help"));
        // The closure in here will actually never run, because when this program is
        // run from gui, the "--gui" will always be false and the else path will be taken
        klask::run_app(app, Settings::default(), |_| {});
    } else {
        // The acutal code
        println!("{:?}", App::parse())
    }
}

```

**Comment by Eolien55** [comment]
Well, this works, but I thought of it as the default feature for recognizing wether the program is a gui or started by the gui (opposed to having a environment variable to determine it). IMO, it's a better default, since turning a CLI program into a GUI one disables the CLI use, except in case where the user of klask do things like the one you proposed. I think it would be quite easy to modify the app to include the desired flags, and useful (I repeat myself, I know) since a GUI and a CLI live in the same binary.

I understand that Klask's raison-d'être is to turn CLIs into GUIs, but losing the CLI makes me a bit sad. I also understand that this isn't necessarily a feature used by all users. However, it would make Klask more appealing to me.

Anyway, thanks for you dedication. Have a great day !

**Comment by Eolien55** [comment]
To be clear, I meant this as a crate-level feature, rather than a user-level one.

**Comment by MichalGniadek** [comment]
Sorry if I came off as dismissive in my previous answer.
I would expect most uses of `klask` are to make a cli app more accessible to people not experienced in command line. So based on this, making the gui just launch without any flags seems like the better default. And if someone needs to, there's the (kinda hacky) way to launch gui from cli in my answer above. 
Also, previously I was using subcommands to differentiate between the main app and the child app, but it was changed to an environment variable because it was less invasive (e.g. when someone wanted to parse the arguments themselves).

Thanks for the interest in this library!

**Comment by Eolien55** [comment]
Ok I get all of that. I agree, forcing CLI isn't a good idea, and adding options might be invasive. I would suggest the use of crate features for adding optional --cli flag rather than a --gui flag, or maybe using CLI flags to build GUI fields state ?

Maybe it's a bad idea ? I don't really know, and I hope I gave you some ideas.

I can't wait for clap v3 to come out so that I can use your crate ! Cheers
