### ISSUE TITLE
[Question] Compilation into WASM

### ISSUE THREAD

**Issue by OpoOpo** [MichalGniadek/klask#23]
Hi,
I was wondering if there is a way to compile the GUI created with klask into WASM.
I found out that underlying egui supports it, but I don't know exactly what else has to be done to work meaning with changing of the renderer, bindgen, etc.

Thank you :-)

**Comment by MichalGniadek** [comment]
From what I have found out by some quick googling, `std::process::command`, which I'm using to launch the “proper” app, won't work on WASM. But otherwise (and if clap itself works on WASM) it might work? I'm not sure, to be honest, and I don't have much experience working with WASM.

**Comment by OpoOpo** [comment]
I do not have either :-(.
Because I wrote some application and person I distributed to have MAC and I am unable to compile the application from Linux to MAC successfully (I can produce library, but I the person told me that does not run...) so I thought that the WASM could be a way out :-D.
If this is the case, when I get the courage I'll try 60fps or something like this for proper GUI (I hate creating GUIs, that's why the klask is a holy grail for me :-D )

**Comment by barafael** [comment]
@OpoOpo see https://github.com/MichalGniadek/klask/pull/57 for some updates on this topic :)
