### ISSUE TITLE
Support for languages other than English

### ISSUE THREAD

**Issue by cppxor2arr** [MichalGniadek/klask#26]
For example the text hint for optional arguments shows as "*(Optional)*" and it's hard coded.

For now I guess I could add a patch in Cargo.toml to change the source code.

**Comment by MichalGniadek** [comment]
Hi, sorry for the wait. I have added localization settings, if you pull from github instead of crates.io (`klask = { git = "https://github.com/MichalGniadek/klask"}`) you can try them out. There's also a new example showing it off, that you can check out.

**Comment by cppxor2arr** [comment]
It works great.
