### ISSUE TITLE
File chooser hangs on Mac OS

### ISSUE THREAD

**Issue by alexjago** [MichalGniadek/klask#27]
Hi, 

The file chooser currently hangs on Mac OS. This is _probably_ downstream from 
https://github.com/balthild/native-dialog-rs/issues/23

Happily, it looks like they've fixed that, or at least made progress on it, as of version 0.6.2 — so upgrading the dependency version is hopefully all that's needed.

**Comment by MichalGniadek** [comment]
Hi, I have updated some dependencies. I don't have a mac to try it on, so could you try changing your `cargo.toml` to contain `klask = { git = "https://github.com/MichalGniadek/klask"}` and see if it still hangs?

**Comment by alexjago** [comment]
That seems to work as expected in my app!

Please feel free to ping me whenever you'd like to test `klask` on Mac. 

(P.S. `clap` is already up to 3.0.5 from 3.0.0)

**Comment by MichalGniadek** [comment]
Yeah, I know, but I think there is some kind of bug with non-ascii struct field names with clap <3.0.0. I didn't get around to making an issue on clap yet, so I just kept it at 3.0.0.

**Comment by alexjago** [comment]
Fair enough. I'll close this issue - looks like it's fixed.
