### ISSUE TITLE
Allow for different styles

### ISSUE THREAD

**Issue by Zeddicus414** [MichalGniadek/klask#28]
Hi Michal,

I was actually thinking about building this exact tool before learning that you had already done it! Very awesome, especially considering that I don't have the necessary Rust skills to even attempt it yet.

For me, a significant downside of this tool is that the default egui style is fairly small, thin lettering with low contrast. 

Here is an example of my VSCode setup demonstrating higher contrast small fonts in the explorer panel and much higher contrast larger fonts in the code:
![image](https://user-images.githubusercontent.com/31261142/149607116-08a5ee6c-6abd-4f0a-b82a-1ceefd165e96.png)

Would it be possible to allow for some configurable style options?

I'd be interested in helping do this, but I literally just figured out how to set some style options in the egui hello_world, so I'm not sure if this is beyond me or not.

Thanks,
Zed

**Comment by MichalGniadek** [comment]
Hi, thanks! And sorry for the wait, I have added styling options to the settings. You can check it out if pull the latest commit from github! (`klask = { git = "https://github.com/MichalGniadek/klask"}`)
