### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by 1Dragoon** [MichalGniadek/klask#30]
Is there any way to use this with async code? If so, any code examples of how to use it with run_derived?

**Comment by MichalGniadek** [comment]
I don't have any experience with async code, so I'm not sure. Have you tried something already? Or can you give an example code how you would expect this to work?

**Comment by 1Dragoon** [comment]
Yeah I couldn't get it to work with anything I did in tokio where the main function is async. Sadly I can't share the code for this particular project as it has some potentially sensitive bits. I'll try to come up with an analog

**Comment by barafael** [comment]
@1Dragoon you could do this: check out what `#[tokio::main]` actually does, it just creates a runtime and then launches it. You could do this yourself in a function that is called by your actual main function (which parses before the CLI args).

**Comment by barafael** [comment]
@1Dragoon here's an example of how you could do it:
https://github.com/barafael/achat/blob/27a91729abd42216bfadc44a4a9dcab4c1ce732b/bin/dump_client_gui.rs#L7
Notably, you can

```rust
    klask::run_derived::<Args, _>(Settings::default(), |args| {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap()
            .block_on(async { dump_server(args).await.unwrap() });
    });
```

**Comment by barafael** [comment]
I suppose this may be closed. @MichalGniadek what do you think?

**Comment by 1Dragoon** [comment]
Oh yeah sorry I've been busy, this works. Thanks!
