### ISSUE TITLE
Progress bar panics

### ISSUE THREAD

**Issue by barafael** [MichalGniadek/klask#31]
Hi,
we're making a simple fractal renderer and at some point wanted to try klask. It's brilliant :D 
I tried implementing a progress bar by calling `klask::output::progress_bar` with my approximate progress. It compiles, but when I run, I get panic in this line: https://github.com/MichalGniadek/klask/blob/c6b1544b5c1dd25a7c950a0969e569ecfae5f926/src/output.rs#L181
The text in the iterator doesn't seem to be the expected text in the `Some` arm, instead it's sth. like `Some("124568479524573")`. 
I was able to reproduce this a number of times.
Later trying to reproduce it while filing this issue, I wasn't able to reproduce it anymore :/
Instead, I got this: 
![image](https://user-images.githubusercontent.com/6966738/153751645-c74e607a-f587-409b-a73b-a5e8674229be.png)
After which the application freezes.
I'll post the repo link as soon as we switch it to public if you are interested.

**Comment by MichalGniadek** [comment]
Hmmmm, that's weird. It seems that the first progress bar shows up but not the later updates. 
- What is the description of the progress bar?
- Are you using anywhere unicode character `\u{5FFFE}`? (It's a non-character and doesn't have a proper representation. I'm using it in my makeshift protocol for sending the progress bars)
- Are there multiple threads printing stuff to stdout? Or are you doing anything non-standard with stdout?

**Comment by barafael** [comment]
Ok, update. All stdout weirdness was me being dumb - I had replaced the klask git crate with a local version, where I had placed debug prints. Sorry if this startled you!!!

It's now back to the previous behaviour. I get:
```rust
[/some/path/klask/src/output.rs:171] iter.next() = Some(
    "5831526316684989411",
)
```
I get the same number I think every time, maybe it's a hash?

My progress bar code is this: 

```rust
klask::output::progress_bar(
    "progress-bar",
    count.load(Ordering::Relaxed) as f32 / num_pixels as f32,
);
```

**Comment by MichalGniadek** [comment]
Yeah, it's a hash for identifying a specific progress bar. I looked through the code but didn't find anything, so I can't really help you without a minimal example, a public repo or some other way of reproducing the issue.

**Comment by barafael** [comment]
Fair enough! There ya go: https://github.com/barafael/klask-progressbar-panic

**Comment by MichalGniadek** [comment]
The problem was with rayon, and more specifically with writes from multiple threads. I changed the code, so now it locks stdout before writing anything. I pushed it to github so you check if it fixes your issue! (it fixes it in the minimal example)

Although you will probably want to change it anyway because it's a massive slowdown. Minimal example without the progress bar finishes instantly, but with the progress bars it takes a good few seconds. You should probably update it less frequently.

**Comment by barafael** [comment]
Thanks so much! Good points on performance, probably updating once a second is fine.
