### ISSUE TITLE
Currently not possible to use stdin while program is running

### ISSUE THREAD

**Issue by barafael** [MichalGniadek/klask#37]
I don't know how hard this would be, but it would be useful to me if the area in the main window where stdout is displayed also supported entering text into stdin. Specifically, I klask-ified a program which was using `rustyline`, a `readline`-like crate. Of course this gets into the realm of terminal emulators (?) so might be quite challenging, but anyway here goes the suggestion, feel free to close if not in scope.

**Comment by MichalGniadek** [comment]
Unfortunately, I don't think there is an easy way to implement this. It would require more terminal-emulator machinery (I have played with it on other projects, and it was challenging with a lot of edge cases). Also, it might be problematic on the interface end (e.g., I don't think egui supports colored edit fields).

But thanks for the suggestion and for trying out klask!

**Comment by barafael** [comment]
For the record, the normal enable_stdin on the Settings works well enough for me for most cases!

**Comment by MichalGniadek** [comment]
I'm glad to hear that!
