### ISSUE TITLE
Random panic

### ISSUE THREAD

**Issue by barafael** [MichalGniadek/klask#40]
Hi,

I may have encountered a random panic. I'm not sure what I was doing just before, unfortunately, and only have a screenshot:
![image](https://user-images.githubusercontent.com/6966738/178150281-4141996c-8e6e-4a56-9226-b3b974063b73.png)
The code:
https://github.com/cocomundo/julia-set-renderer (run with `cargo run` for klask GUI).
I suspect it has something to do with hitting the "Kill" button while a progressbar is being displayed. But I haven't been able to get it to crash again with this.
Specifically, on this commit: https://github.com/cocomundo/julia-set-renderer/commit/22dc76605663bed7187532221f0104516c6f9261 but I don't think it makes a difference.

**Comment by MichalGniadek** [comment]
Progress bars are currently implemented very... poorly, it's basically parsing stdout and looking for some specific characters that no normal application should use. I implemented some changes in #49 that remove the panic that was the cause of this crash. The output will probably be garbage if it happens again, but it's a better alternative to crashing the whole application.
